var texts = [
    //Premier Texte
    ``,
    //Second texte
    `
    La pratique de Nathalie Joiris est multiforme, et se partage entre sculptures, dessins, installations, art public, vidéos et montage photographiques, ou encore œuvres numériques et interactives. Cette variété est le résultat d’un travail de recherche en continuel développement, qui ne saurait se contenter d’un seul et unique médium. C’est aussi le reflet du désir de l’artiste de parvenir à une parfaite adéquation entre la forme et le fond, entre son message et la ou les technique(s) utilisée(s) pour lui donner vie (ou pour mieux feindre de le faire, comme c’est le cas dans la série des Sculptures rêvées, ou des Villes pensées, montages infographiques d’œuvres a priori irréalisables, intégrées dans des lieux bien réels). Son exposition à la Médiatine offre un panorama très complet des différentes facettes de ce travail, et permet de l’appréhender dans toute sa complexité et sa variété. <br> <br>

    Il est toutefois une constante chez Nathalie Joiris  : l’intérêt qu’elle porte au monde végétal. Les arbres occupent une place centrale dans ses œuvres conçues pour l’espace public, où ils entrent en dialogue avec des éléments de diverse nature (Due to leave, installée au croisement de la Zavelstraat à Koertenberg, en donne un très bon exemple). Mais dans ses installations également, l’artiste a souvent recours à des végétaux, qui jouent un rôle central dans l’élaboration de subtiles métaphores visuelles. L’incursion de la nature dans les arts plastiques (dont le Land Art constitue la forme la plus radicale), participe d’une réflexion plus large sur le rapport de l’humanité à l’univers et au passage du temps. Nathalie Joiris s’inscrit dans cette démarche, en y ajoutant parfois (cela n’a rien d’un système) les éléments d’un discours plus spécifiquement féminin. Lorsqu’elle procède de la sorte, l’artiste préfère l’allégorie à la revendication, dissimulant son message entre les formes au point de le rendre quasi inaperçu, ce qui a pour effet de le renforcer lorsqu’il s’impose à l’esprit du spectateur. <br><br>

    Son œuvre intitulée 123… PIANO, qui accueille le visiteur dans l’exposition, est une parfaite illustration de ces recherches. Conçue pour être présentée au sol, elle se compose de panneaux de bois formant une surface rectangulaire noire séparée en deux parties par une résistance électrique, et bordée sur chaque côté de petits ventilateurs. La présence des visiteurs, détectée par des capteurs infrarouges, provoque le démarrage du dispositif. Le vent des hélices et les courants d’air qui traversent la pièce, font se mouvoir sur les panneaux des petites boules de paina – fibre cotonneuse qui enveloppe les graines d’un arbre subtropical, le paineira –, en un ballet ludique et désordonné. De manière imperceptible, les boules sont lentement dirigées vers le centre et la résistance électrique qui s’allume soudain, les enflammant en un instant. «  End of the game  !  », comme aime à le dire l’artiste à propos de cette œuvre, dont le titre est emprunté à un jeu d’enfants. Pour le spectateur, l’interruption brutale de ce qui semblait n’être qu’un spectacle anodin crée un sentiment de malaise, ce qui est précisément le but recherché par Nathalie Joiris. Il s’agit pour elle de parler, sur le ton de la métaphore, «  des femmes dans le monde qui ne peuvent décider de
    leur vie et passent sans transition du statut de petite fille à celle de mère  ». Toute l’installation est tournée vers l’évocation de «  l'impact physique et social de ce passage  ; dualité par excellence où cohabitent à la fois tensions douces, fluides, ludiques, dures, violentes, joyeuses, tristes, dangereuses, fatalistes, mortelles  ».

    Très différente dans sa mise en forme, l’installation En fin de compte qui pense à nous traite d’un sujet également lié à la place de la femme dans la société. Ces gros ballons dont les spectateurs doivent se saisir – les embrasser, littéralement –, contiennent un dispositif interactif qui donne à entendre des récits liés à la féminité écrits et contés par des hommes et des femmes conviés par l'artiste à prendre part au processus créatif. Le titre devient alors très explicite, qui fait référence à un système patriarcal dans lequel la femme est trop souvent oubliée. Le but de Nathalie Joiris est de poursuivre l’élaboration de l’œuvre en continuant de collecter des témoignages, donc en multipliant le nombre de ballons, les petits récits s’additionnant pour composer une histoire de la féminité qui reste à écrire. Ici également, le spectateur joue un rôle central. Et s’il prend part à l’œuvre sur une base volontaire – le fait de soulever le ballon et de le tenir serré contre lui –, il ne peut prévoir quel sera le résultat de cette action, la surprise que lui réserve l’artiste.

    La réflexion de Nathalie Joiris sur la dichotomie masculin/féminin présente en chacun(e) d’entre nous, trouve un écho dans deux installations a priori fort différentes, mais réunie par le thème de l’altérité. Dans une vidéo, elle danse et bouge avec son ombre, en un ballet improvisé baigné d’une lumière à peine perceptible  : qui, de l’artiste ou de sa «  part d’ombre  » est l’autre  ? Ailleurs, dans une petite pièce faiblement éclairée par une seule ampoule, deux panneaux peints en noir se font face, et ne reflètent que les parties dénudées des visiteurs  : bras, jambes et visages créent des taches blafardes en mouvement, qui brouillent la perception que nous avons habituellement de notre propre corps, qui se mêle ici à celui des autres personnes présentes à nos côtés.

    Si le miroir a toujours été associé dans l’histoire de l’art occidental au thème de la vanité, alors ce non-miroir en négatif devrait, peut-être, nous protéger des aléas du temps qui passe. Cette thématique est abordée de manière très directe dans une œuvre qui se compose de deux petits carrousels fixés au plafond, sur lesquels tourne lentement, pour le premier, un arbuste vivant et, pour le second, un petit arbre mort tourné vers le bas sur lequel est accroché des figurines de pendus. Deux temporalités se font face  : celle du végétal et celle de l’humain. Mais tandis que les arbres continuent habituellement de croître celui-ci, comme pris de compassion, semble vouloir accompagner le supplicié dans la mort. 

    Après ce passage sombre, la vie reprend ses droits dans un espace brillamment éclairé, couvert de terre, et dans lequel croissent toutes sortes de cucurbitacées. Il s’agit pour Nathalie Joiris de les apprivoiser dans le temps, en les incitant à se rendre toujours plus loin dans la pièce, tout en filmant leurs efforts en gros plan. Les images de cette lente croissance sont alors retransmises sur un écran dans l’espace d’exposition, sans qu’il ne soit possible dans un premier temps de l' interpréter. L’humain et le végétal sont ici enfin réunis, tant les formes particulières de ces plantes sont pour l’artiste évocatrices des expressions d’un visage. Cette œuvre, qui ne manque évidemment pas d’humour, clôt la boucle initiée avec 123… PIANO  : si elle utilise la technologie numérique (le réseau de webcams), elle se compose majoritairement d’éléments végétaux, mais nécessite pourtant une attention soutenue tout au long de l’exposition, à la manière d’une œuvre technologique.

    Nathalie Joiris aime souligner comment son utilisation du monde végétal reflète sa préoccupation de «  poser un regard sur nous et notre monde  », afin de «  mettre en évidence notre relation au temps qui nous taraude, ce temps qui scande imperturbablement le mouvement naturel de la vie.  » Nul doute que son exposition à la Médiatine, pour laquelle elle aura bénéficié d’espaces nombreux et variés, lui aura permis d’expliciter son propos.

    `
    ,
    //Troisième texte
    `
    Symbole sŽculaire largement partagŽ ˆ l'Žchelle planŽtaire, l'arbre est, en cette fin de millŽnaire, l'objet d'approches plastiques diverses, refltant des prŽoccupations parfois trŽs diffŽrenciŽes. 
    L'enracinement dans le sol et sa lente montŽe vers le ciel le place ˆ la conjonction de dŽmarches foisonnantes.(...)
    
    Dans ce contexte, Nathalie Joiris occupe une place en marge. Son discours, sensible au besoin de protection de la biosphre s'accompagne Žgalement d'une mise en garde contre toute dŽrive Žcologiste totalitaire. "Il ne faudrait pas, Žcrit-elle, sous le couvert d'une urgence Žcologique et la qute d'une nature originelle, en arriver ˆ enfermer la nature(...)dans des zones interdites. Nous passerions de la suprŽmatie de l'Humain ˆ celle de la nature. C'est ˆ une relation de complŽmentaritŽ et d'enrichissement mutuel que nous devons arriver. (...)
    Cet Žquilibre souhaitable trouve une formulation plastique originale dans ses sculptures dont les matŽriaux de prŽdilection sont des jeunes pousses d'arbre.
    Leurs croissances contribuent au dŽveloppement de la sculpture, la charge d'une affectivitŽ lourde liŽes ˆ ses diverses attributions symboliques et individuelles.
    
    Toutefois, le dŽveloppement de l'arbre est contrariŽ par des interventions de l'artiste qui l'obligent ˆ pousser courbŽ, enfermŽ dans une cage de bois, ˆ traverser un grillage, ˆ grandir entre deux pierres de granite.
    L'oeuvre peut alors choquer, dŽranger ou susciter un malaise. Mais ces malaises obligent ˆ s'interroger sur leurs origines, leurs enjeux Žthiques: si l'on peut tre blessŽ par la flexion imposŽe ˆ un arbre, ˆ quelle situation est-on par contre insensibles? Et quelles valeurs dŽterminent ces attitudes diffŽrenciŽes?
    
    En formulant des idŽes de tensions, de contraction, de flŽchissement ou d'Žcartement, Nathalie Joiris aborde les rivages de la condition humaine; ses oeuvres parlent aussi de l'Homme, entendu dans ses rapports multiples et complexes avec le monde. (2000)
    
    Au-delˆ de leurs enjeux politico-moraux, les oeuvres de Nathalie Joiris constituent un langage introspectif, ouvert au partage comme au dialogue.
    "Les mŽmoires de moments", arbres aux racines prises dans un noeud de corde, alimentŽs par baxter et accrochŽs aux murs, induisent des Žtats psychiques variables qui peuvent s'Žtendre de l'angoisse de la maladie ˆ la protection animiste.
    Les "valises", cageots de bois ˆ poignŽe et d'o dŽpassent les feuilles, suggrent le voyage, le nomadisme, le dŽracinement vŽcu ou non comme un drame (hors de terre, ses arbres continuent ˆ vivre), mais comme la libertŽ de s'Žpanouir en tout lieu.
    
    
    Pierre-Olivier Rollin 2000
    `
]